// <auto-generated />
using System;
using AutoInsuranceAndClaimManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoInsuranceAndClaimManagement.Migrations
{
    [DbContext(typeof(AutoInsuranceAndClaimManagementDbContext))]
    [Migration("20221222072658_mg")]
    partial class mg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Accident", b =>
                {
                    b.Property<int>("Accident_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accident_Location");

                    b.Property<string>("Accident_Reason");

                    b.Property<int>("Vehicle_Id");

                    b.HasKey("Accident_Id");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("Accident");
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Claim", b =>
                {
                    b.Property<int>("Claim_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Approved_Amount");

                    b.Property<DateTime>("Approved_Date");

                    b.Property<int>("Claim_Amount");

                    b.Property<string>("Claim_Status");

                    b.Property<int>("Vehicle_Id");

                    b.HasKey("Claim_Id");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Customer", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Blood_Group");

                    b.Property<string>("Confirm_Password");

                    b.Property<string>("Customer_Name");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Email");

                    b.Property<string>("Gender");

                    b.Property<string>("Password");

                    b.Property<string>("Phone_Num");

                    b.HasKey("Customer_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Policy", b =>
                {
                    b.Property<int>("Policy_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aadhar_Num");

                    b.Property<DateTime>("End_Date");

                    b.Property<int>("Policy_Amount");

                    b.Property<string>("Policy_Type");

                    b.Property<DateTime>("Start_Date");

                    b.Property<int>("Vehicle_Id");

                    b.Property<string>("policy_Status");

                    b.HasKey("Policy_Id");

                    b.HasIndex("Vehicle_Id");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<int>("Customer_Id");

                    b.Property<string>("Manufacturer");

                    b.Property<DateTime>("Register_Date");

                    b.Property<string>("Register_Num");

                    b.Property<int>("Vehicle_CC");

                    b.Property<string>("Vehicle_Name");

                    b.Property<string>("Vehicle_Type");

                    b.Property<string>("Vehicle_UsuageType");

                    b.HasKey("Vehicle_Id");

                    b.HasIndex("Customer_Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Accident", b =>
                {
                    b.HasOne("AutoInsuranceAndClaimManagement.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Claim", b =>
                {
                    b.HasOne("AutoInsuranceAndClaimManagement.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Policy", b =>
                {
                    b.HasOne("AutoInsuranceAndClaimManagement.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("Vehicle_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AutoInsuranceAndClaimManagement.Models.Vehicle", b =>
                {
                    b.HasOne("AutoInsuranceAndClaimManagement.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
